[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flastik"
dynamic = ["version"]
description = "A Flask-like Tiny-framework for static websites"
readme = "README.md"
authors = [
    { name = "Dr. Thomas Roc", email = "info@electricbrain.fr" }
]
requires-python = ">=3.10"
dependencies = ["jinja2", "docutils"]

[project.optional-dependencies]
test = ["pytest"]
docs = ["reportlab"]

[project.scripts]
flastik = "flastik.cli:main"

[tool.setuptools.dynamic]
version = { attr = "flastik.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = ["flastik"]

[tool.setuptools.package-data]
flastik = [
    "README.pdf",
    "LICENSE.txt",
    "base_templates/*",
    "doc_templates/*",
    "bootstrap/BOOTSTRAP_LICENSE",
    "bootstrap/css/*",
    "bootstrap/js/*",
]
