name: Ruff Lint and Format

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Ruff Check
        run: pre-commit run ruff-check --all-files
        env:
          RUFF_OUTPUT_FORMAT: github
      - name: Ruff Format
        run: pre-commit run ruff-format --all-files --show-diff-on-failure
